/**
 * SEED DATA
 * ──────────
 * Realistic Thailand-based financial profile for demo purposes.
 * Based on a Bangkok professional with a mortgage, PVD, RMF investments,
 * and various lifestyle expenses.
 */

import { v4 as uuid } from "uuid";
import type {
  Profile, IncomeItem, ExpenseItem, DebtAccount,
  InvestmentAccount, RetirementAssumptions, TaxAssumptions, Scenario,
} from "./types";

const today = new Date();
const thisYear = today.getFullYear();

export const seedProfile: Profile = {
  id: uuid(),
  fullName: "Somchai",
  dateOfBirth: "1990-03-15",          // Age ~36
  retirementAge: 55,
  lifeExpectancy: 90,
  country: "Thailand",
  currency: "THB",
  planningStartDate: `${thisYear}-01-01`,
  maritalStatus: "Single",
  householdNotes: "Bangkok-based IT professional. Owns a condo with mortgage.",
  emergencyFundTargetMonths: 6,
  targetMinCashBalance: 200_000,
  riskProfile: "moderate",
  notes: "Priority: pay off mortgage early. Secondary: build retirement portfolio.",
  currentCashBalance: 350_000,
};

export const seedIncomes: IncomeItem[] = [
  {
    id: uuid(),
    name: "Monthly Salary (After Tax)",
    category: "salary",
    owner: "Somchai",
    frequency: "monthly",
    amount: 85_000,
    startDate: "2021-01-01",
    annualGrowthRate: 0.04,
    isTaxable: false,          // after-tax for cash-flow, gross handled in tax module
    notes: "Demo salary — not real data",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Annual Performance Bonus",
    category: "bonus",
    owner: "Somchai",
    frequency: "yearly",
    amount: 120_000,
    startDate: "2021-01-01",
    annualGrowthRate: 0.03,
    isTaxable: true,
    notes: "Demo bonus — typically paid in Q1",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Freelance / Consulting",
    category: "freelance",
    owner: "Somchai",
    frequency: "monthly",
    amount: 12_000,
    startDate: `${thisYear}-01-01`,
    annualGrowthRate: 0.05,
    isTaxable: true,
    notes: "Demo side income — not real data",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Investment Dividends",
    category: "dividend",
    owner: "Somchai",
    frequency: "yearly",
    amount: 18_000,
    startDate: "2023-01-01",
    annualGrowthRate: 0.03,
    isTaxable: true,
    notes: "Demo dividend income — not real data",
    isActive: true,
  },
];

export const seedExpenses: ExpenseItem[] = [
  {
    id: uuid(), name: "Utilities (Electric, Water)", category: "Utilities",
    amount: 2_500, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: true,
    notes: "Demo — condo utilities", isActive: true, budgetAmount: 2_800,
  },
  {
    id: uuid(), name: "Mobile & Internet", category: "Utilities",
    amount: 1_200, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.02, isEssential: true,
    notes: "Demo — mobile + home fiber", isActive: true, budgetAmount: 1_200,
  },
  {
    id: uuid(), name: "Groceries & Dining", category: "Food",
    amount: 12_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.035, isEssential: true,
    notes: "Mix of cooking at home and eating out", isActive: true, budgetAmount: 12_000,
  },
  {
    id: uuid(), name: "Transport (BTS/Grab/Fuel)", category: "Transport",
    amount: 5_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: true,
    notes: "Mostly BTS and occasional Grab", isActive: true, budgetAmount: 5_500,
  },
  {
    id: uuid(), name: "Life & Health Insurance", category: "Insurance",
    amount: 30_000, frequency: "yearly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.05, isEssential: true,
    notes: "Term life + health top-up", isActive: true, budgetAmount: 30_000,
  },
  {
    id: uuid(), name: "Condo Common Fee + Maintenance", category: "Housing",
    amount: 4_500, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: true,
    notes: "Monthly common fee + small repairs budget", isActive: true, budgetAmount: 5_000,
  },
  {
    id: uuid(), name: "Subscriptions (Netflix, Spotify, etc.)", category: "Entertainment",
    amount: 1_500, frequency: "monthly", owner: "Somchai",
    startDate: "2021-01-01", inflationRate: 0.05, isEssential: false,
    notes: "Streaming + software subscriptions", isActive: true, budgetAmount: 1_500,
  },
  {
    id: uuid(), name: "Shopping & Personal Care", category: "Shopping",
    amount: 8_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: false,
    notes: "Clothes, grooming, misc", isActive: true, budgetAmount: 8_000,
  },
  {
    id: uuid(), name: "Travel (Domestic & International)", category: "Travel",
    amount: 120_000, frequency: "yearly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.04, isEssential: false,
    notes: "2-3 trips per year", isActive: true, budgetAmount: 100_000,
  },
  {
    id: uuid(), name: "Family Support", category: "Family",
    amount: 10_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.02, isEssential: true,
    notes: "Monthly support to parents in province", isActive: true, budgetAmount: 10_000,
  },
  {
    id: uuid(), name: "Pet Care (Dog)", category: "Pet",
    amount: 4_000, frequency: "monthly", owner: "Somchai",
    startDate: "2021-06-01", inflationRate: 0.04, isEssential: true,
    notes: "Food, vet, grooming", isActive: true, budgetAmount: 4_000,
  },
  {
    id: uuid(), name: "Gym & Fitness", category: "Health",
    amount: 1_800, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: false,
    notes: "Fitness center membership", isActive: true, budgetAmount: 1_800,
  },
  {
    id: uuid(), name: "Annual Car Service & Registration", category: "Transport",
    amount: 15_000, frequency: "yearly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.03, isEssential: true,
    notes: "Car service + annual registration", isActive: true, budgetAmount: 15_000,
  },
  {
    id: uuid(), name: "PVD Contribution (5% salary)", category: "Investment",
    amount: 6_000, frequency: "monthly", owner: "Somchai",
    startDate: "2020-01-01", inflationRate: 0.04, isEssential: true,
    notes: "Employee PVD at 5% of gross ~120K", isActive: true,
  },
  {
    id: uuid(), name: "RMF Annual Investment", category: "Investment",
    amount: 60_000, frequency: "yearly", owner: "Somchai",
    startDate: "2022-01-01", inflationRate: 0.0, isEssential: false,
    notes: "For tax deduction - target max benefit", isActive: true,
  },
];

export const seedDebts: DebtAccount[] = [
  {
    id: uuid(),
    name: "Debt-1 – Primary Home Mortgage",
    lender: "Sample Bank A",
    debtType: "mortgage",
    originalPrincipal: 5_500_000,
    currentBalance: 5_120_000,
    annualInterestRate: 0.035,
    interestType: "floating",
    minimumMonthlyPayment: 32_000,
    standardMonthlyPayment: 32_000,
    extraMonthlyPayment: 0,
    startDate: "2021-01-01",
    loanTermMonths: 360,
    propertyName: "Sample Home",
    annualPrepayment: 0,
    notes: "Primary home mortgage. Demo data — not real.",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Debt-2 – Personal Loan",
    lender: "Sample Bank A",
    debtType: "personal-loan",
    originalPrincipal: 400_000,
    currentBalance: 340_000,
    annualInterestRate: 0.045,
    interestType: "fixed",
    minimumMonthlyPayment: 5_000,
    standardMonthlyPayment: 5_000,
    extraMonthlyPayment: 0,
    startDate: "2023-01-01",
    loanTermMonths: 84,
    notes: "Multi-purpose personal loan. Demo data — not real.",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Debt-3 – Investment Condo Mortgage",
    lender: "Sample Bank B",
    debtType: "mortgage",
    originalPrincipal: 3_200_000,
    currentBalance: 2_850_000,
    annualInterestRate: 0.042,
    interestType: "floating",
    minimumMonthlyPayment: 22_000,
    standardMonthlyPayment: 22_000,
    extraMonthlyPayment: 0,
    startDate: "2022-01-01",
    loanTermMonths: 300,
    propertyName: "Sample Condo",
    notes: "Investment condo mortgage. Demo data — not real.",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Debt-4 – Car Loan",
    lender: "Sample Finance Co.",
    debtType: "personal-loan",
    originalPrincipal: 900_000,
    currentBalance: 620_000,
    annualInterestRate: 0.028,
    interestType: "fixed",
    minimumMonthlyPayment: 15_000,
    standardMonthlyPayment: 15_000,
    extraMonthlyPayment: 0,
    startDate: "2023-06-01",
    loanTermMonths: 72,
    propertyName: "",
    notes: "Car financing loan. Demo data — not real.",
    isActive: true,
  },
];


export const seedInvestments: InvestmentAccount[] = [
  {
    id: uuid(),
    name: "PVD – Company Provident Fund",
    accountType: "PVD",
    assetDescription: "Mixed fund (60% equity / 40% bond)",
    marketValue: 280_000,
    currency: "THB",
    isTaxAdvantaged: true,
    expectedAnnualReturn: 0.06,
    monthlyContribution: 5_000,
    annualContribution: 60_000,
    owner: "Somchai",
    notes: "Demo PVD — 5% employee + 5% employer match",
    isActive: true,
  },
  {
    id: uuid(),
    name: "RMF – Sample RMF Equity Fund",
    accountType: "RMF",
    assetDescription: "Thai equity RMF",
    marketValue: 150_000,
    currency: "THB",
    isTaxAdvantaged: true,
    expectedAnnualReturn: 0.08,
    monthlyContribution: 0,
    annualContribution: 50_000,
    owner: "Somchai",
    notes: "Demo RMF — annual contribution for tax deduction",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Brokerage – Stocks & ETFs",
    accountType: "brokerage",
    assetDescription: "SET50 ETF + individual stocks",
    marketValue: 200_000,
    currency: "THB",
    isTaxAdvantaged: false,
    expectedAnnualReturn: 0.09,
    monthlyContribution: 5_000,
    annualContribution: 60_000,
    owner: "Somchai",
    notes: "Demo brokerage — long-term wealth building",
    isActive: true,
  },
  {
    id: uuid(),
    name: "SSO Savings Account",
    accountType: "SSO",
    assetDescription: "Social Security Office benefit",
    marketValue: 75_000,
    currency: "THB",
    isTaxAdvantaged: true,
    expectedAnnualReturn: 0.03,
    monthlyContribution: 0,
    annualContribution: 0,
    owner: "Somchai",
    notes: "Demo SSO — government contributions",
    isActive: true,
  },
  {
    id: uuid(),
    name: "Emergency Fund (High-Yield Savings)",
    accountType: "savings",
    assetDescription: "High-yield savings account",
    marketValue: 180_000,
    currency: "THB",
    isTaxAdvantaged: false,
    expectedAnnualReturn: 0.015,
    monthlyContribution: 5_000,
    annualContribution: 60_000,
    owner: "Somchai",
    notes: "Demo emergency fund — target 6 months expenses",
    isActive: true,
  },
];

export const seedRetirement: RetirementAssumptions = {
  retirementAge: 55,
  expectedAnnualExpense: 600_000,    // 50K/month in today's money (demo)
  inflationRate: 0.03,
  portfolioReturnPreRetirement: 0.07,
  portfolioReturnDuringRetirement: 0.05,
  safeWithdrawalRate: 0.04,
  pensionMonthlyAmount: 0,
  ssoMonthlyBenefit: 7_500,         // estimated SSO pension
};

export const seedTax: TaxAssumptions = {
  annualGrossIncome: 1_200_000,      // ~100K/month gross (demo data)
  personalDeduction: 60_000,
  employmentIncomeDeduction: 100_000, // capped at 100K
  pvdContribution: 60_000,
  rmfContribution: 50_000,
  ssfContribution: 0,
  lifeInsurancePremium: 20_000,
  healthInsurancePremium: 10_000,
  mortgageInterestDeduction: 50_000, // estimated annual interest portion
  parentalDeduction: 60_000,         // 2 parents × 30,000
  childDeduction: 0,
  otherDeductions: 0,
  annualBonus: 120_000,
};

const now = new Date().getFullYear();
const colorPalette = ["#3b82f6","#10b981","#ef4444","#8b5cf6","#f59e0b","#06b6d4","#f97316","#ec4899","#14b8a6","#a855f7"];

export const seedScenarios: Scenario[] = [
  {
    id: "base",
    name: "Base Case",
    description: "Current plan: salary growth 4%, inflation 3%, extra 5K/month to mortgage",
    isBase: true,
    color: "#3b82f6",
    tag: "custom",
    clusters: ["Wealth Accumulation & Growth", "Income & Compensation"],
    riskLevel: "medium",
    timeHorizon: "long",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.03,
      investmentReturnRate: 0.07,
      mortgageExtraMonthlyPayment: 5_000,
      annualLumpSumPrepayment: 50_000,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "aggressive-paydown",
    name: "Aggressive Mortgage Paydown",
    description: "Pay extra 20,000/month + 100K annual lump sum to accelerate payoff",
    isBase: false,
    color: "#10b981",
    tag: "custom",
    clusters: ["Wealth Accumulation & Growth"],
    riskLevel: "low",
    timeHorizon: "medium",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.03,
      investmentReturnRate: 0.05,
      mortgageExtraMonthlyPayment: 20_000,
      annualLumpSumPrepayment: 100_000,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "income-shock",
    name: "Income Shock",
    description: "Job loss / income cut by 50% for 12 months starting next year",
    isBase: false,
    color: "#ef4444",
    tag: "bad",
    clusters: ["Risk Management & Stability", "Income & Compensation"],
    riskLevel: "high",
    timeHorizon: "short",
    assumptions: {
      incomeGrowthRate: 0.02,
      inflationRate: 0.035,
      investmentReturnRate: 0.06,
      mortgageExtraMonthlyPayment: 0,
      annualLumpSumPrepayment: 0,
      incomeShockYear: now + 1,
      incomeShockFactor: 0.5,
      incomeShockDuration: 12,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "refinance-2yr",
    name: "Refinance in 2 Years",
    description: "Refinance mortgage at 5.5% in 2 years, continue extra payments",
    isBase: false,
    color: "#8b5cf6",
    tag: "custom",
    clusters: ["Wealth Accumulation & Growth", "Income & Compensation"],
    riskLevel: "low",
    timeHorizon: "medium",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.03,
      investmentReturnRate: 0.07,
      mortgageExtraMonthlyPayment: 5_000,
      refinanceYear: now + 2,
      refinanceRate: 0.055,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "retirement-first",
    name: "Retirement First",
    description: "Maximize investment contributions, reduce extra mortgage payment",
    isBase: false,
    color: "#f59e0b",
    tag: "custom",
    clusters: ["Wealth Accumulation & Growth", "Income & Compensation"],
    riskLevel: "medium",
    timeHorizon: "long",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.03,
      investmentReturnRate: 0.09,
      mortgageExtraMonthlyPayment: 0,
      annualLumpSumPrepayment: 0,
      taxReliefInvestmentAmount: 200_000,
    },
    createdAt: new Date().toISOString(),
  },
  // Good scenarios (6-15)
  {
    id: "rates-fall-refi",
    name: "Falling Rates Refi",
    description: "Refinance at 4.0% in 2 years as rates ease",
    isBase: false,
    color: "#3b82f6",
    tag: "good",
    clusters: ["Risk Management & Stability"],
    riskLevel: "low",
    timeHorizon: "medium",
    assumptions: {
      incomeGrowthRate: 0.04,
      inflationRate: 0.025,
      investmentReturnRate: 0.07,
      mortgageExtraMonthlyPayment: 5_000,
      refinanceYear: now + 2,
      refinanceRate: 0.04,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "bull-decade",
    name: "Bull Market Decade",
    description: "Sustained 10% portfolio returns",
    isBase: false,
    color: "#10b981",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth"],
    riskLevel: "medium",
    timeHorizon: "long",
    assumptions: {
      incomeGrowthRate: 0.05,
      inflationRate: 0.025,
      investmentReturnRate: 0.10,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "tame-inflation",
    name: "Inflation Tamed",
    description: "CPI back to 1.5%",
    isBase: false,
    color: "#ef4444",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth"],
    riskLevel: "low",
    timeHorizon: "long",
    assumptions: {
      inflationRate: 0.015,
      expenseInflationOverride: 0.015,
      investmentReturnRate: 0.075,
      incomeGrowthRate: 0.04,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "mega-bonus",
    name: "Mega Bonus Year",
    description: "One-off ฿500K bonus, 200K to mortgage",
    isBase: false,
    color: "#8b5cf6",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth", "Income & Compensation"],
    riskLevel: "low",
    timeHorizon: "short",
    assumptions: {
      annualBonusAmount: 500_000,
      annualLumpSumPrepayment: 200_000,
      investmentReturnRate: 0.07,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "career-surge",
    name: "Career Surge",
    description: "+20% pay bump in year 3",
    isBase: false,
    color: "#f59e0b",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth", "Income & Compensation"],
    riskLevel: "low",
    timeHorizon: "medium",
    assumptions: {
      salaryRaiseYear: now + 3,
      salaryRaiseFactor: 1.20,
      incomeGrowthRate: 0.05,
      investmentReturnRate: 0.07,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "inheritance",
    name: "Inheritance Windfall",
    description: "฿1M lump in year 5",
    isBase: false,
    color: "#06b6d4",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth"],
    riskLevel: "low",
    timeHorizon: "medium",
    assumptions: {
      windfallYear: now + 5,
      windfallAmount: 1_000_000,
      annualLumpSumPrepayment: 100_000,
      investmentReturnRate: 0.07,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "tax-reform-rmf",
    name: "Tax Reform Win",
    description: "Max RMF/SSF every year",
    isBase: false,
    color: "#f97316",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth"],
    riskLevel: "low",
    timeHorizon: "long",
    assumptions: {
      taxReliefInvestmentAmount: 500_000,
      investmentReturnRate: 0.075,
      incomeGrowthRate: 0.04,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "mortgage-free-5y",
    name: "Mortgage Free in 5",
    description: "Aggressive ฿50K/mo extra",
    isBase: false,
    color: "#ec4899",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth"],
    riskLevel: "low",
    timeHorizon: "medium",
    assumptions: {
      mortgageExtraMonthlyPayment: 50_000,
      annualLumpSumPrepayment: 100_000,
      investmentReturnRate: 0.06,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "fire-50",
    name: "FIRE at 50",
    description: "Cut expenses, max contribs, retire early",
    isBase: false,
    color: "#14b8a6",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth", "Income & Compensation"],
    riskLevel: "medium",
    timeHorizon: "long",
    assumptions: {
      retirementAge: 50,
      expenseInflationOverride: 0.02,
      taxReliefInvestmentAmount: 500_000,
      investmentReturnRate: 0.08,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "dual-income",
    name: "Dual-Income Household",
    description: "Spouse income year 2",
    isBase: false,
    color: "#a855f7",
    tag: "good",
    clusters: ["Wealth Accumulation & Growth", "Income & Compensation"],
    riskLevel: "low",
    timeHorizon: "long",
    assumptions: {
      salaryRaiseYear: now + 2,
      salaryRaiseFactor: 1.40,
      mortgageExtraMonthlyPayment: 15_000,
      investmentReturnRate: 0.07,
    },
    createdAt: new Date().toISOString(),
  },
  // Bad scenarios (16-20)
  {
    id: "stagflation",
    name: "Stagflation",
    description: "7% inflation, 3% returns",
    isBase: false,
    color: "#3b82f6",
    tag: "bad",
    clusters: ["Risk Management & Stability"],
    riskLevel: "high",
    timeHorizon: "long",
    assumptions: {
      inflationRate: 0.07,
      expenseInflationOverride: 0.07,
      investmentReturnRate: 0.03,
      incomeGrowthRate: 0.02,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "rate-hike-shock",
    name: "Rate Hike Shock",
    description: "Mortgage rate +3% next year",
    isBase: false,
    color: "#10b981",
    tag: "bad",
    clusters: ["Risk Management & Stability"],
    riskLevel: "high",
    timeHorizon: "short",
    assumptions: {
      mortgageRateChange: 0.03,
      mortgageRateChangeYear: now + 1,
      mortgageExtraMonthlyPayment: 0,
      investmentReturnRate: 0.05,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "recession-30",
    name: "Recession",
    description: "-30% income for 24 months",
    isBase: false,
    color: "#ef4444",
    tag: "bad",
    clusters: ["Risk Management & Stability", "Income & Compensation"],
    riskLevel: "high",
    timeHorizon: "medium",
    assumptions: {
      incomeShockYear: now + 2,
      incomeShockFactor: 0.7,
      incomeShockDuration: 24,
      investmentReturnRate: 0.04,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "bear-5y",
    name: "5-Year Bear Market",
    description: "2% returns for 5 years",
    isBase: false,
    color: "#8b5cf6",
    tag: "bad",
    clusters: ["Risk Management & Stability"],
    riskLevel: "high",
    timeHorizon: "long",
    assumptions: {
      investmentReturnRate: 0.02,
      investmentVolatility: 0.20,
      inflationRate: 0.035,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "health-shock",
    name: "Health Emergency",
    description: "฿500K out-of-pocket year 2",
    isBase: false,
    color: "#f59e0b",
    tag: "bad",
    clusters: ["Risk Management & Stability"],
    riskLevel: "high",
    timeHorizon: "short",
    assumptions: {
      oneTimeExpenses: [{ year: now + 2, amount: 500_000, description: "Medical" }],
      investmentReturnRate: 0.06,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "job-loss-6mo",
    name: "Job Loss",
    description: "6-month full income loss next year",
    isBase: false,
    color: "#06b6d4",
    tag: "bad",
    clusters: ["Risk Management & Stability", "Income & Compensation"],
    riskLevel: "high",
    timeHorizon: "short",
    assumptions: {
      incomeShockYear: now + 1,
      incomeShockFactor: 0,
      incomeShockDuration: 6,
      investmentReturnRate: 0.05,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "housing-bust",
    name: "Housing Bust",
    description: "Refi delayed, rate +2%",
    isBase: false,
    color: "#f97316",
    tag: "bad",
    clusters: ["Risk Management & Stability"],
    riskLevel: "high",
    timeHorizon: "medium",
    assumptions: {
      mortgageRateChange: 0.02,
      mortgageRateChangeYear: now + 1,
      refinanceYear: now + 5,
      investmentReturnRate: 0.04,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "layoff-restart",
    name: "Layoff & Restart",
    description: "-40% 18 months, then recover",
    isBase: false,
    color: "#ec4899",
    tag: "bad",
    clusters: ["Risk Management & Stability", "Income & Compensation"],
    riskLevel: "high",
    timeHorizon: "medium",
    assumptions: {
      incomeShockYear: now + 1,
      incomeShockFactor: 0.6,
      incomeShockDuration: 18,
      salaryRaiseYear: now + 3,
      salaryRaiseFactor: 1.10,
      investmentReturnRate: 0.05,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "hyperinflation",
    name: "Hyperinflation",
    description: "10% CPI, real wages -3%",
    isBase: false,
    color: "#14b8a6",
    tag: "bad",
    clusters: ["Risk Management & Stability"],
    riskLevel: "high",
    timeHorizon: "long",
    assumptions: {
      inflationRate: 0.10,
      expenseInflationOverride: 0.10,
      incomeGrowthRate: 0.07,
      investmentReturnRate: 0.04,
    },
    createdAt: new Date().toISOString(),
  },
  {
    id: "late-retire-70",
    name: "Late Retirement at 70",
    description: "Push retirement out",
    isBase: false,
    color: "#a855f7",
    tag: "bad",
    clusters: ["Risk Management & Stability", "Income & Compensation"],
    riskLevel: "high",
    timeHorizon: "long",
    assumptions: {
      retirementAge: 70,
      investmentReturnRate: 0.045,
      inflationRate: 0.04,
      incomeGrowthRate: 0.03,
    },
    createdAt: new Date().toISOString(),
  },
];
