name = "email-notify"
account_id = "db5a4404320982f9d7866822c09a2ba8"
main = "gmail-worker.js"
compatibility_date = "2024-09-23"
compatibility_flags = ["nodejs_compat"]

# No routes needed --- we call it directly at
# https://email-notify.<your-subdomain>.workers.dev

# Secrets are set via: wrangler secret put <NAME> --config email-wrangler.toml
